#!/bin/sh
    # sh  ~/bin/kncydia   Creating a Repository
# dpkg-scanpackages: info: Wrote 1 entries to output Packages file.
# python -m SimpleHTTPServer 8088
# ~/cydia
# 192.168.2.77 - - [06/Feb/2018 18:36:03] "GET /debs/.deb HTTP/1.1" 200 -

function kncydia(){
    # 建立index
    cd ~/cydia 
    rm -rf ~/cydia/Packages.bz
    rm -rf ~/cydia/Packages.bz2
    rm  -rf ~/cydia/Packages
    # Packages去掉路径前缀
    dpkg-scanpackages debs /dev/null > Packages
# 利用 bzip2 生成 Cydia 可以识别的文件格式
bzip2 ~/cydia/Packages

# tar zcvf Packages.gz Packages
# bzip2 -k Packages Packages.bz2
# 制作 Release【Optional】
}

kncydia

open ~/cydia

python -m SimpleHTTPServer 8088
open http://127.0.0.1:8088/cydia/

#  部署方式 ~/cydia 下执行python -m SimpleHTTPServer 8088  ，cydia 添加http://192.168.2.189:8088/ 源即可
exit 0