#!/bin/sh
    # sh  ~/bin/kncydia   Creating a Repository
# dpkg-scanpackages: info: Wrote 1 entries to output Packages file.
# python -m SimpleHTTPServer 8088
# ~/cydia
# 192.168.2.77 - - [06/Feb/2018 18:36:03] "GET /debs/.deb HTTP/1.1" 200 -

cd  ~/cydia

python -m SimpleHTTPServer 8088
open http://127.0.0.1:8088/cydia/
#  部署方式 ~/cydia 下执行python -m SimpleHTTPServer 8088  ，cydia 添加http://192.168.2.189:8088/ 源即可
exit 0