#!/bin/sh
# iphone 的配置Start Cydia and add Frida’s repository by navigating to Manage -> Sources -> Edit -> Add and entering https://build.frida.re
# frida-ps -Uai 查看，来获取参数
# devzkndeMBP:bin devzkn$ frida-ps -Ua
  # PID  Name       Identifier        
# -----  ---------  ------------------
# 14790  App Store  com.apple.AppStore
# usage: devzkndeMacBook-Pro:~ devzkn$ kndump 邮件
# ./dump.py 'App Store'
# dump app   
echo "" > ~/.ssh/known_hosts
cd ~/decrypted/frida-ios-dump-master 
rm -rf ./Payload
./dump.py $1
open .
exit 0