#!/bin/sh
#➜  bin git config --global user.email "eamil@qq.com"
#➜  bin git config --list                            
#➜  bin git config --global user.name mac            
#1.Checkout
git checkout --orphan latest_branch

#2. Add all the files
git add -A

#3. Commit the changes
git commit -am "commit message"

#4. Delete the branch
git branch -D master

#5.Rename the current branch to master
git branch -m master

#6.Finally, force update your repository

git remote remove origin
git init

exit 0