#!/bin/bash
echo "==================MonkeyDev(create ipa file...)=================="
# cd `dirname $0`;
rm -rf ./Target.ipa;
rm -rf ./Payload; 
mkdir Payload; 
APP=$(find . -type d | grep ".app$" | head -n 1)
cp -rf "$APP" ./Payload; 
data="`date +%F-%T-%N`"
postName="$data"-".ipa"
zip -r -q "$postName" ./Payload; 
rm -rf ./Payload;
open .
# 移动ipa包到特定目录
cp -a "$postName" /Users/devzkn/Downloads/wxPayload
open /Users/devzkn/Downloads/wxPayload
echo "==================MonkeyDev(done)=================="
exit;